### PR TITLE
Adding support for dates

### PR DESCRIPTION
**Pull request by ppallesws**
Will this be of use?

### CODE REVIEW

**Comment by andyhu** [comment]
+1 for adding date support

**Comment by caridy** [comment]
@ppallesws can you sign the CLA?

**Comment by ppallesws** [comment]
Sure. System reply...Good to see you, Pete Palles

You previously signed this CLA on:
Tue Dec 09 2014 21:08:01 GMT+0000 (UTC)


___________________________
Pete Palles
RevTechPlus
Director of Technology
Cell:  (570) 640-9589
www.revtechplus.com

**Comment by ericf** [comment]
@ppallesws Thanks for doing this! Would you be up for adding unit tests for this new date support?

**Comment by ppallesws** [comment]
Sure, I can give it a look this evening if no urgency.

___________________________
Pete Palles
RevTechPlus
Director of Technology
Cell:  (570) 640-9589
www.revtechplus.com

**Comment by ericf** [comment]
This approach won't work, see #16

**Pull request closed without merging**
